import type { Issue, IdentityGroup, Race } from './types';

export const ISSUES: Issue[] = [
  { id: 'immigration', label: 'Immigration', icon: '🌎' },
  { id: 'education', label: 'Education', icon: '📚' },
  { id: 'healthcare', label: 'Healthcare', icon: '🏥' },
  { id: 'housing', label: 'Housing', icon: '🏠' },
  { id: 'criminal_justice', label: 'Criminal Justice', icon: '⚖' },
  { id: 'economy', label: 'Economy & Jobs', icon: '💰' },
  { id: 'environment', label: 'Environment', icon: '🌱' },
  { id: 'voting_rights', label: 'Voting Rights', icon: '🗳' },
  { id: 'gun_policy', label: 'Gun Policy', icon: '🔰' },
  { id: 'reproductive_rights', label: 'Reproductive Rights', icon: '⚕' },
  { id: 'lgbtq', label: 'LGBTQ+ Rights', icon: '🏳' },
  { id: 'budget', label: 'Budget & Taxes', icon: '📈' },
];

export const IDENTITY_GROUPS: IdentityGroup[] = [
  { id: 'teachers_union', label: 'Teachers Unions', icon: '📚', type: 'Labor' },
  { id: 'nurses_union', label: 'Nurses / Healthcare Workers', icon: '🩺', type: 'Labor' },
  { id: 'afl_cio', label: 'AFL-CIO', icon: '⚖', type: 'Labor' },
  { id: 'sierra_club', label: 'Sierra Club', icon: '🌳', type: 'Environmental' },
  { id: 'lwv', label: 'League of Women Voters', icon: '🗳', type: 'Civic' },
  { id: 'naacp', label: 'NAACP', icon: '✊', type: 'Civil Rights' },
  { id: 'lulac', label: 'LULAC', icon: '🌎', type: 'Civil Rights' },
  { id: 'planned_parenthood', label: 'Planned Parenthood', icon: '💙', type: 'Healthcare' },
  { id: 'emily_list', label: "EMILY's List", icon: '☆', type: 'Women' },
  { id: 'chamber_commerce', label: 'Chamber of Commerce', icon: '🏢', type: 'Business' },
  { id: 'nra', label: 'NRA', icon: '🔰', type: 'Gun Rights' },
  { id: 'texas_right_to_life', label: 'Texas Right to Life', icon: '✝', type: 'Pro-Life' },
  { id: 'fw_star_telegram', label: 'Star-Telegram Editorial', icon: '📰', type: 'Newspaper' },
  { id: 'texas_tribune', label: 'Texas Tribune', icon: '📰', type: 'Newspaper' },
];

export const RACES: Race[] = [
  {
    id: 'us_senate_tx',
    name: 'U.S. Senate',
    position: 'US Senator',
    type: 'federal',
    candidates: [
      {
        name: 'Jasmine Crockett',
        party: 'Democratic',
        incumbent: false,
        initials: 'JC',
        issues: {
          immigration: { position: 'Supports pathway to citizenship for undocumented immigrants; opposes border wall expansion', source: 'Campaign website' },
          education: { position: 'Advocates for increased public school funding, student debt relief, universal pre-K', source: 'Legislative record (TX House)' },
          healthcare: { position: 'Supports expanding Medicaid in Texas, lowering prescription drug costs', source: 'Campaign website' },
          criminal_justice: { position: 'Led criminal justice reform bills in TX House; supports ending cash bail', source: 'TX Legislature voting record' },
          economy: { position: 'Supports raising federal minimum wage, small business tax credits', source: 'Campaign platform' },
          reproductive_rights: { position: 'Pro-choice; opposes Texas abortion restrictions; supports restoring Roe protections', source: 'Public statements' },
          voting_rights: { position: 'Authored voting access legislation in TX House; opposes voter ID restrictions', source: 'Legislative record' },
          gun_policy: { position: 'Supports universal background checks and red flag laws', source: 'Campaign website' },
          lgbtq: { position: 'Supports Equality Act and anti-discrimination protections', source: 'Public statements' },
          housing: { position: 'Supports federal affordable housing investment and renter protections', source: 'Campaign platform' },
        },
        endorsements: ['naacp', 'emily_list', 'teachers_union', 'afl_cio', 'planned_parenthood', 'lwv'],
      },
      {
        name: 'James Talarico',
        party: 'Democratic',
        incumbent: false,
        initials: 'JT',
        issues: {
          education: { position: 'Former teacher; championed public school funding and teacher pay raises in TX House', source: 'Legislative record (TX House)' },
          healthcare: { position: 'Supports Medicaid expansion and mental health funding', source: 'Campaign website' },
          immigration: { position: 'Supports comprehensive immigration reform with earned legalization', source: 'Campaign website' },
          environment: { position: 'Supports clean energy transition and grid reliability investments', source: 'Legislative record' },
          economy: { position: 'Focus on workforce development, community college investment', source: 'Campaign platform' },
          gun_policy: { position: 'Supports raising age to purchase firearms, universal background checks', source: 'TX Legislature voting record' },
          reproductive_rights: { position: 'Pro-choice; opposes state abortion restrictions', source: 'Public statements' },
          voting_rights: { position: 'Supports automatic voter registration and expanded early voting', source: 'Campaign website' },
          housing: { position: 'Supports affordable housing tax credits and anti-displacement measures', source: 'Campaign platform' },
        },
        endorsements: ['teachers_union', 'sierra_club', 'lwv', 'planned_parenthood'],
      },
    ],
  },
  {
    id: 'tarrant_county_judge',
    name: 'Tarrant County Judge',
    position: 'County Judge',
    type: 'local',
    candidates: [
      {
        name: "Tim O'Hare",
        party: 'Republican',
        incumbent: true,
        initials: 'TO',
        issues: {
          immigration: { position: 'Championed local anti-illegal-immigration ordinances; supports stricter enforcement', source: 'County records, news coverage' },
          budget: { position: 'Cut county budget, reduced property tax rate', source: 'Tarrant County budget records' },
          criminal_justice: { position: 'Supports law enforcement funding increases; opposes bail reform', source: 'Public statements' },
          education: { position: 'Supports school choice and parental rights in curriculum', source: 'Public statements' },
          lgbtq: { position: 'Opposed library materials with LGBTQ+ content; supported restrictions', source: 'County meeting minutes' },
          gun_policy: { position: 'Strong Second Amendment supporter; opposes new gun regulations', source: 'NRA endorsement' },
        },
        endorsements: ['nra', 'texas_right_to_life', 'chamber_commerce'],
      },
      {
        name: 'Robert Buker',
        party: 'Republican',
        incumbent: false,
        initials: 'RB',
        issues: {
          budget: { position: 'Promises fiscal responsibility, transparent county spending', source: 'Campaign website' },
          criminal_justice: { position: 'Supports law enforcement; focus on reducing property crime', source: 'Campaign platform' },
          housing: { position: 'Wants to streamline permitting to increase housing supply', source: 'Campaign website' },
        },
        endorsements: [],
      },
      {
        name: 'Lydia Bean',
        party: 'Democratic',
        incumbent: false,
        initials: 'LB',
        issues: {
          healthcare: { position: 'Supports county health programs expansion, mental health services', source: 'Campaign website' },
          housing: { position: 'Advocates for affordable housing investment and tenant protections', source: 'Campaign platform' },
          criminal_justice: { position: 'Supports diversion programs and mental health courts', source: 'Campaign website' },
          education: { position: 'Supports public school funding, opposes book bans', source: 'Public statements' },
          budget: { position: 'Wants increased transparency in county spending; supports investing in infrastructure', source: 'Campaign platform' },
          environment: { position: 'Supports county climate resilience planning', source: 'Campaign website' },
          voting_rights: { position: 'Supports expanded early voting locations in Tarrant County', source: 'Campaign platform' },
        },
        endorsements: ['lwv', 'teachers_union', 'sierra_club'],
      },
    ],
  },
  {
    id: 'tarrant_commissioner_p1',
    name: 'Tarrant County Commissioner, Pct. 1',
    position: 'County Commissioner',
    type: 'local',
    candidates: [
      {
        name: 'Alisa Simmons',
        party: 'Democratic',
        incumbent: true,
        initials: 'AS',
        issues: {
          healthcare: { position: 'Expanded county health services; supported JPS Hospital funding', source: 'County voting record' },
          housing: { position: 'Championed affordable housing initiatives in Precinct 1', source: 'Commissioner office records' },
          budget: { position: 'Voted for infrastructure investments; supports progressive revenue', source: 'County budget votes' },
          criminal_justice: { position: 'Supports re-entry programs and community-based safety', source: 'Public statements' },
        },
        endorsements: ['naacp', 'afl_cio', 'lwv'],
      },
      {
        name: 'Tony Tinderholt',
        party: 'Republican',
        incumbent: false,
        initials: 'TT',
        issues: {
          budget: { position: 'Wants to cut county spending; opposes tax increases', source: 'Campaign website' },
          immigration: { position: 'Former state rep who authored strict immigration enforcement bills', source: 'TX Legislature record' },
          gun_policy: { position: 'Authored constitutional carry legislation in TX House', source: 'Legislative record' },
          criminal_justice: { position: 'Supports increased law enforcement funding', source: 'Campaign platform' },
          reproductive_rights: { position: 'Authored bill to criminalize abortion with no exceptions', source: 'TX Legislature record' },
        },
        endorsements: ['nra', 'texas_right_to_life'],
      },
    ],
  },
  {
    id: 'tarrant_district_clerk',
    name: 'Tarrant County District Clerk',
    position: 'District Clerk',
    type: 'local',
    candidates: [
      {
        name: 'Phil Sorrells',
        party: 'Republican',
        incumbent: true,
        initials: 'PS',
        issues: {
          criminal_justice: { position: 'Modernized case filing systems; reduced processing backlogs', source: 'Office records' },
          budget: { position: 'Reduced office operating costs while maintaining services', source: 'County budget reports' },
        },
        endorsements: ['fw_star_telegram'],
      },
      {
        name: 'Tiffany Burks',
        party: 'Democratic',
        incumbent: false,
        initials: 'TB',
        issues: {
          criminal_justice: { position: 'Wants to improve public access to court records, reduce wait times', source: 'Campaign website' },
          voting_rights: { position: 'Supports making jury selection more representative of community demographics', source: 'Campaign platform' },
        },
        endorsements: ['naacp'],
      },
    ],
  },
  {
    id: 'tarrant_county_clerk',
    name: 'Tarrant County Clerk',
    position: 'County Clerk',
    type: 'local',
    candidates: [
      {
        name: 'Tom Wilder',
        party: 'Republican',
        incumbent: true,
        initials: 'TW',
        issues: {
          budget: { position: 'Maintained efficient operations; digitized many county records', source: 'Office annual reports' },
          voting_rights: { position: 'Managed county elections; implemented voter ID requirements', source: 'County records' },
        },
        endorsements: ['chamber_commerce'],
      },
      {
        name: 'Nathan Smith',
        party: 'Democratic',
        incumbent: false,
        initials: 'NS',
        issues: {
          voting_rights: { position: 'Wants more polling locations, extended hours, multilingual support', source: 'Campaign website' },
          budget: { position: 'Supports investing in technology to improve county services', source: 'Campaign platform' },
        },
        endorsements: ['lulac', 'lwv'],
      },
    ],
  },
  {
    id: 'tx_house_90',
    name: 'Texas House District 90',
    position: 'State Representative',
    type: 'state',
    candidates: [
      {
        name: 'Ramon Romero Jr.',
        party: 'Democratic',
        incumbent: true,
        initials: 'RR',
        issues: {
          education: { position: 'Voted for public school funding increases; opposes voucher programs', source: 'TX Legislature voting record' },
          healthcare: { position: 'Supports Medicaid expansion for Texas', source: 'Legislative record' },
          immigration: { position: 'Opposes SB4-style enforcement bills; supports immigrant communities', source: 'Voting record' },
          economy: { position: 'Supports small business grants and workforce training for District 90', source: 'Office records' },
          housing: { position: 'Authored bill for property tax relief for elderly homeowners', source: 'Legislative record' },
        },
        endorsements: ['lulac', 'teachers_union', 'afl_cio'],
      },
    ],
  },
  {
    id: 'tx_house_95',
    name: 'Texas House District 95',
    position: 'State Representative',
    type: 'state',
    candidates: [
      {
        name: 'Nicole Collier',
        party: 'Democratic',
        incumbent: true,
        initials: 'NC',
        issues: {
          criminal_justice: { position: 'Chairs Criminal Jurisprudence committee; led bail reform and re-entry legislation', source: 'TX Legislature committee records' },
          education: { position: 'Supports increased teacher pay and public school funding', source: 'Voting record' },
          healthcare: { position: 'Supports expanding access to mental health services', source: 'Legislative record' },
          gun_policy: { position: 'Supports background check requirements and safe storage laws', source: 'Voting record' },
          voting_rights: { position: 'Opposed restrictive voting bills; supports expanded access', source: 'Legislative record' },
        },
        endorsements: ['naacp', 'emily_list', 'planned_parenthood', 'teachers_union'],
      },
    ],
  },
];
